spring:
  web:
    resources:
      static-locations:
        - "file:src/main/resources/static/"
        - "classpath:/static/"
  jpa:
    open-in-view: false

springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html
