spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  sql:
    init:
      schema-locations: classpath:db/schema-h2.sql
springdoc:
  swagger-ui:
    path: /api/v1/swagger-ui.html
